name: Releases

on:
  repository_dispatch:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
     - name: checkout
     - uses: actions/checkout@v2
     - run: |
         zip -r release.0.0.0.1.zip ./
         ls -l -c
     - uses: ncipollo/release-action@v1
     - with:
          tag: "tag nimashadiao"
          name: "shit"
          artifacts: "release.tar.gz,foo/*.txt"
          bodyFile: "release.0.0.0.1.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
